#!/bin/bash 
yum install -y gcc libffi-devel python-devel openssl-devel gmp-devel libxml2-devel libxslt-devel postgresql-devel redhat-rpm-config git python-pip wget
&&
wget -q -O- https://raw.githubusercontent.com/openstack/rally/master/install_rally.sh | bash
